---
title: "Xplorer: Convenient Data Exploration with see() and browse()"
author: "Florian Simon Schaffner"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Vignette Title} 
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---


This vignette explains the rationale behind writing `Xplorer`, compares it to other packages and provides examples for using `see()` and `browse()`.

# see()

`see()` prints the following details of an object to the console:

- attributes (useful to inspect labels)
- class, typeof, mode, storage.mode
- table (frequency and percentage of values)
- summary statistics

There are several other packages which attempt to do someting similar, but none of them offers the ease of use and thourough inspection of ojects. For example, base R offers the functions `summary()`, `str()` and `structure()`. However, each of those is limited in what they display and leave other aspects untouched. `see()` combines a number of functions that would have to be invoked seperately and mirrors Stata's 'codebook'. 

`see()`is an S3 generic and currently comes with the following data types:

* character
* factor
* numeric
* data.frame
* labelled
* default (all other types)

## Example

```{r}
# Create example data
numeric.labelled <- c(1, 2, 2, 3, 3, 3, 4, 4, 4, 4)
attr(numeric.labelled, "label") <- "mylabel"

library("Xplorer")
see(numeric.labelled)
```


# browse()

The aim of `browse()` is twofold. First, it allows you to search variables in a data frame based on their names and contents in Rstudio, which is currently not possible. Second, it puts the summary statistics of each variable into a data.frame. This way it goes beyond `summary()`, `str()` and `structure()`.









